config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users

  root to: 'pages#home'
  get '/desinations/display_unbooked_destinations', to: 'destinations#display_unbooked_destinations'
  get '/bookings/index', to: 'bookings#index'
  resources :destinations, only: [:create, :edit, :index, :destroy, :show, :new,:update] do
    resources :bookings, only: [:new, :create, :show,:destroy]
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_attachment :photo
  belongs_to :user
  has_many :bookings
  validates :name, uniqueness: true, presence: true

  def self.search(search)
    where("name LIKE ?","%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :destinations
  has_attachment :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_destination, only:[:show, :new, :create, :destroy]
  before_action :set_booking ,only:[:show, :destroy]
  # before_action :set_user, only: [:index, :create]


  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.destination = @destination
    if @booking.save
      @destination.booked = !@destination.booked
      @destination.save
      redirect_to destinations_path
    else
      render :new
    end
  end



  def show
  end

  def destroy

    @destination.booked = !@destination.booked
    @destination.save
    @booking.destroy


    redirect_to bookings_index_path
  end

  def index
    @bookings = Booking.where(user_id: current_user)
    @created_destination = Destination.where(user: current_user)
  end


  private

  def set_destination
    @destination = Destination.find(params[:destination_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
  def booking_params
    params.require(:booking).permit(:end_date, :start_date)

  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:destination_booked,:show, :edit, :update, :destroy]

  def index
    @destinations = Destination.all
    if params[:search]
      if Destination.search(params[:search]).any?
      @destinations = Destination.search(params[:search])
      else
        flash[:notice]= "result not matching"
        render 'index'
      end
    end
  end

 def show

 end

 # def destination_booked
 #  @destination.booked = !@destination.booked
 #  end

 def display_unbooked_destinations
  @destinations = Destination.where(booked: false)
 end


def edit
end


def new
  @destination = Destination.new
end

def create

 @destination = Destination.new(destination_params)
 @destination.user = current_user
  # if @destination.name == Destination.where(name: @destination.name)
  #   render :new
  # else

      if @destination.save
        redirect_to destinations_path
      else
        render :new
      end

end

def update
  @destination.update(destination_params)

    # no need for app/views/destinations/update.html.erb
    redirect_to destination_path(@destination)
  end

  private

  def set_destination
    @destination = Destination.find(params[:id])
  end
  def destination_params
    params.require(:destination).permit(:name, :price, :description, :planet_type, :weather, :distance, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@user, @destination, @booking] do |m| %>
<%= m.input :start_date %> <br>
<%= m.input :end_date %> <br>
<%= m.submit "Confirm Booking", class: "rounded-red" %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <div class="title-front-dash">
<<<<<<< HEAD






<div class="container ">
   <% if @bookings.empty? %>
=======
      <% if @bookings.empty? %>
>>>>>>> c7006ddb893650e1c3a5ffc0a433d4f846cf8079
      <div class="  text-center">
        <br>
    <p>no <br>booking</p>
      </div>
      <% else %>
      <div class=" title-front text-center">
        <br>
    <p>This is your booked Destinations <br>all over the universe</p>
      </div>
  </div>
      <div class="row">
        <% @bookings.each do |booking| %>
        <div class="col-xs-12 col-sm-12 col-md-12 ">
          <div class="product">
           <div class="card-img product-image " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url(<%= booking.destination.seed_photo ? (image_path booking.destination.seed_photo) : (cl_image_path booking.destination.photo.path) %> );">
          </div>

           <div class="product-body">

            <% if current_user.avatar.nil? %>
            <%= image_tag "rocket.png", class: "avatar card-user-dash hidden-xs", id: "logo" %>
            <% else %>
            <%= cl_image_tag current_user.avatar.path, class: "avatar card-user-dash hidden-xs" %>
            <% end %>
            <div class="product-description">
              <h3><%= booking.destination.name %></h3>

              <p><%= booking.destination.planet_type %></p>
              <p> booked from <%= booking.start_date %> to <%= booking.end_date %></p>
                <br>
              <%= link_to 'Delete Booking', destination_booking_path(booking.destination, booking),method: :delete, class: "btn rounded-black" %>

            </div>
<<<<<<< HEAD

=======
>>>>>>> c7006ddb893650e1c3a5ffc0a433d4f846cf8079
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
</div>


<hr>

<<<<<<< HEAD

=======
>>>>>>> c7006ddb893650e1c3a5ffc0a433d4f846cf8079
  <div class="container ">
    <div class="title-front-dash">
      <% if @created_destination.any? %>
      <div class="text-center">
      <p>This is your Destinations <br>all over the universe</p>
    </div>
      <hr>
    <% else %>
    <div class="text-center">
  <p>Tno <br>all over the universe</p>
      <hr>
    </div>
  <% end %>
   </div>
    <div class="row">
<<<<<<< HEAD

=======
>>>>>>> c7006ddb893650e1c3a5ffc0a433d4f846cf8079


      <% @created_destination.each do |destination| %>


<<<<<<< HEAD

<div class="container ">

  <% if @created_destination.any? %>
  <div class=" title-front text-center">
    <h2>This is your Destinations all over the universe</h2>

  <div class=" title-front-dash">


  <% if @created_destination.any? %>
 <div class=" title-front-dash">


    <p>This is your Destinations <br>all over the universe</p>

    <hr>

  </div>
  <div class="row">


    <% @created_destination.each do |destination| %>


    <div class="col-xs-12 col-sm-6 col-md-4 "
    <div class="card">
     <div class="card-img " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path destination.photo %>);">
     </div>

     <div class="card-block">
      <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/filouzzz">

      <div class="card-description">
        <h2><%= destination.name %></h2>
        <p><%= destination.planet_type %></p>
        <p> booked from <%= booking.start_date %> to <%= booking.end_date %></p>
        <%= link_to 'Edit Destination', edit_destination_path(@destination), class: "btn btn-primary" %>
      </div>

      <% end %>


    <div class="col-xs-12 col-sm-12 col-md-12">


   <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="product">
         <div class="card-img product-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path destination.photo %>);">
         </div>

         <div class="product-body">
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/filouzzz">

=======
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="product">
         <div class="card-img product-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url(<%= destination.seed_photo ? (image_path destination.seed_photo) : (cl_image_path destination.photo.path) %> );">
          </div>

         <div class="product-body">
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/filouzzz">
>>>>>>> c7006ddb893650e1c3a5ffc0a433d4f846cf8079

          <div class="card-user-dash">
            <h2><%= destination.name %></h2>
            <p><%= destination.planet_type %></p>
          </div>

          <%= link_to 'Edit Destination', edit_destination_path(destination), class: "btn rounded-black" %>

        </div>
        <% end %>
      </div>
    </div>
<<<<<<< HEAD

  <% end %>
</div>
</div>


<!-- correct -->



    </div>


  </div>





  <!-- correct -->


</div>

=======
>>>>>>> c7006ddb893650e1c3a5ffc0a433d4f846cf8079
  </div>
</div>

</div>


</div>
</div>
</div>

app/views/bookings/new.html.erb
<div class="card-img " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url(<%= @destination.seed_photo ? (image_path @destination.seed_photo) : (cl_image_path @destination.photo.path) %> );">
         </div>

  <div class="row">

    <div class="col-md-6">
      <div class="descrshowdest" >
          <h3><%= @destination.name%></h3>
          <p> <%= @destination.planet_type %></p>
          <p><%= @destination.description %></p>
          <p><%= @destination.landscape_type %></p>
          <ul class="text-deco-none">
            <li><p>Price: <%= @destination.price %></p></li>
            <li><p>weather description :<%= @destination.weather%></p></li>
          </ul>
        </div>
        </div>

        <div class="col-md-6">
          <div class="BtnShowRight">
          <%= render 'form' %>
          </div>
        </div>
    </div>
  </div>

app/views/bookings/show.html.erb
<div class = "container">
<div class="card-img " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url(<%= destination.seed_photo ? (image_path destination.seed_photo) : (cl_image_path destination.photo.path) %> );">
<h1 class="text-center"><%= @destination.name%></h1><h4 class="text-center"> a <%= @destination.planet_type %></h4>
<h2 class="text-center"><%= @destination.description %></h2>
<h2 class= "text-center"><%= @destination.landscape_type %></h2>
<ul>
  <li><h3 class="text-center">Price: <%= @destination.price %></h3></li>
  <li><h3 class="text-center">weather description :<%= @destination.weather%></h3></li>
</ul>
</div>


</div>

app/views/destinations/_form.html.erb
<%= form_with(model: destination, local: true) do |form| %>
  <% if destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(destination.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
      <% destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :description %>
    <%= form.text_field :description %>

  </div>

  <div class="actions">
    <%= form.submit, class: "rounded-white" %>
  </div>
<% end %>

app/views/destinations/display_unbooked_destinations.html.erb
<%= render 'shared/cards' %>


<div class="top-padding-100 text-center">
</div>

<%= link_to 'Back', destinations_path %>

app/views/destinations/edit.html.erb
<div class="bg-form">
<div class="container ">
  <div class="row">
    <div class="text-center">
      <h2 class="new-header-page"> Update Destination</h2>
    <div class="form-spacing">
      <div class="col-md-4 col-md-offset-4">
        <%= simple_form_for [@destination] do |f| %>
        <%= f.input :name, placeholder: @destination.name, label: false %>
        <%= f.input :planet_type, placeholder: @destination.planet_type , label: false%>
        <%= f.input :price,placeholder: @destination.price, class: "color-white-form", label: false %>
        <%= f.input :weather, placeholder: @destination.weather, label: false %>
        <%= f.input :distance, placeholder: @destination.distance, label: false %>
        <%= f.input :photo, as: :attachinary %>
        <%= f.input :description, placeholder: @destination.description, label: false %>
        <%= f.submit "Confirm update", class: "btn btn-primary rounded-white" %>
        <% end %>
      </div>
    </div>
    </div>
  </div>
</div>
</div>

app/views/destinations/index.html.erb
<div class="container searchsize">
  <div class="row ">
    <div class="ccol-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <br>
      <div class="input-group">

        <span class="input-group-btn">
          <%= submit_tag "Search", class:"btn btn-default  " %>
        </span>
        <%= form_tag(destinations_path, :method => "get", ) do %>
        <%= text_field_tag :search, params[:name], class:"form-control rounded-white-search", placeholder: "Search Destinations" %>

        <% end %>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->
</div>

<%= render 'shared/cards' %>
<br>
<div class="top-padding-100 text-center">
  <% if current_user %>
  <p><%= link_to 'New Destination', new_destination_path, class: "btn btn-primary rounded-black "%></p>
  <% else %>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-primary rounded-red" %>
  </p>
  <% end %>
</div>

app/views/destinations/new.html.erb
<div class="bg-form">
<div class="container ">
  <div class="row">
    <div class="text-center">
      <h2 class="new-destination-header"> NEW DESTINATION</h2>
    <div class="form-spacing">
      <div class="col-md-4 col-md-offset-4">
        <%= simple_form_for [@destination] do |f| %>
        <%= f.input :name, placeholder: 'name', label: false %>
        <%= f.input :planet_type, placeholder: 'planet type', label: false%>
        <%= f.input :price, class: "color-white-form",placeholder: 'price', label: false %>
        <%= f.input :weather, placeholder: 'weather', label: false %>
        <%= f.input :distance, placeholder: 'disatnce', label: false %>
        <div class="file-upload-new-dest text-center">
        <%= f.input :photo, as: :attachinary %>
        </div>
        <%= f.input :description, placeholder: 'description', label: false %>
        <%= f.submit "new space", class: "btn btn-primary rounded-white" %>
        <% end %>
      </div>
    </div>
    </div>
  </div>
</div>
</div>

app/views/destinations/show.html.erb
  <div class="card-img " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url(<%= @destination.seed_photo ? (image_path @destination.seed_photo) : (cl_image_path @destination.photo.path) %> );">
         </div>
    <div class="row">
      <div class="col-md-6">
        <div class="descrshowdest" >
          <h3><%= @destination.name%></h3>
          <p> <%= @destination.planet_type %></p>
          <p><%= @destination.description %></p>
          <p><%= @destination.landscape_type %></p>
          <ul>
            <li><p>

              price: <%= @destination.price %> USD/DAY MAN!!</p></li>
            <li><p>weather description :<%= @destination.weather%></p></li>
          </ul>
        </div>
        </div>
       <div class="col-md-6">
          <div class="BtnShowRight">
          <%= link_to 'Back', destinations_path, class: "btn rounded-black"%>

          <% if current_user %>
            <% if @destination.booked == false %>

<<<<<<< HEAD
             <%= link_to 'Book', new_destination_booking_path(@destination), class: "btn rounded-red"%>
=======
            <%= link_to 'Book', new_destination_booking_path(@destination), class: "btn rounded-red"%>
>>>>>>> c7006ddb893650e1c3a5ffc0a433d4f846cf8079

            <% end %>
          <% else %>
          <%= link_to 'Log in', new_user_session_path, class: "btn rounded-red"%>
          <% end %>


        <% if @destination.user == current_user %>
        <p>
          <%= link_to 'Update destination', edit_destination_path(@destination), class: "btn btn-primary"  %>
        </p>
        <% else %>
        <% end %>
        </div>
    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Starent</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>


  <%= render 'shared/navbar' %>
   <% if flash[:notice] %>
    <div class="alert alert-info fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-error fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:alert] %>
    </div>
  <% end %>


  <%= yield %>

  <%= render 'shared/footer' %>

  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
  <!-- kjhkukhu -->
</body>
</html>

app/views/pages/home.html.erb
<%= render "shared/wrapper" %>

app/views/shared/_cards.html.erb
<div class="container ">
  <div class=" title-front text-center">
    <h2>Thes are our Destinations all over the universe</h2>
  </div>
  <div class="row">


      <% @destinations.each do |destination| %>

      <div class="col-xs-12 col-sm-6 col-md-4 ">
       <%= link_to destination_path(destination), class:" link-cards" do %>
        <div class="card">
         <div class="card-img " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url(<%= destination.seed_photo ? (image_path destination.seed_photo) : (cl_image_path destination.photo.path) %> );">
         </div>


         <div class="card-block">
          <img class="card-user" src="<%= destination.user.photo %>">

          <div class="card-description">
            <h2><%= destination.name %></h2>
            <p><%= destination.planet_type %></p>
          </div>
          <% if destination.booked == true %>
          <div class="text-center card-text:last-child">
            <span class=" btn rounded-black-dest">Already booked</span>
          </div>
          <% else %>
          <div class="text-center card-text:last-child">
            <% if current_user %>
              <%= link_to 'Book me', new_destination_booking_path(destination), class: "btn rounded-red-dest"%>
            <% end %>
          </div>

          <% end %>
          <% end %>
          <!-- correct -->

        </div>
      </div>
    </div>
    <% end %>

</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links hidden-sm hidden-xs">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <%= image_tag "logo_full.png", class: "img-footer-size"  %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo150x150.png", id: "logo" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <%= link_to "All destinations",'/destinations', class:"navbar-wagon-item navbar-wagon-link" %>

    <%= link_to "Available destinations",'/desinations/display_unbooked_destinations', class:"navbar-wagon-item navbar-wagon-link" %>


      <% if current_user %>

      <%= link_to "#{current_user.first_name} dashboard", bookings_index_path, class:"navbar-wagon-item navbar-wagon-link"%>

      <% end %>
    </a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">

      <div class="dropdown">
        <% if current_user.nil? || current_user.avatar.nil? %>
        <%= image_tag "rocket.png", class: "avatar dropdown-toggle", id: "logo", data: { toggle: "dropdown" } %>
        <% else %>
        <%= cl_image_tag current_user.avatar.path, class: "avatar dropdown-toggle", id: "logo", data: { toggle: "dropdown" } %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li> <%= link_to "Sign up", new_user_registration_path %></li>
          <li> <%= link_to "Log in", new_user_session_path %></li>
          <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li> <%= link_to "Sign up", new_user_registration_path %></li>
        <li> <%= link_to "Log in", new_user_session_path %></li>
        <li> <%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_wrapper.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://media.giphy.com/media/DZD6OikL9NHxK/giphy.gif');">
  <div class="banner-content">
    <h1>**Starent**</h1>
    <p>Rent a planet with us </p>
    <p><%=  link_to 'Show destinations', destinations_path, class: "btn btn-primary btn-lg btnwraper "%></p>
    <% if current_user.nil? %>
    <p><%=  link_to 'Login', new_user_session_path, class: "btn btn-primary  btnwraper "%></p>
    <% end %>

  </div>
</div>